#!/bin/ksh

# mkphlog - a utility to ease the creation of phlogs.
#           Organizes phlog posts in separate directories.
# Created by octotep; anyone can distribute, modify, and 
# share this file however they please.
#
# Version 0.5
#
# Please note, all date strings are in the form of mm/dd/yy(yy)

# The base of the entire gopher site.
# SDF default: $HOME/gopher
gopherRoot="$HOME/gopher"

# The name of the phlog directory (contained in $gopherHome)
phlogDirName="phlog"

# Current working directory of the script
cwd=$(pwd)

# File name for a post
postFile=""

# Default editor, unless the user has one specified in env
editor=${EDITOR:-nano}

# Default timezone, unless the user has one specified in env
TZ=${TZ:-UTC}

# Controls whether the post is automatically added to the main 
# phlog page. If so, Each entry looks like: "BlabBlabBlab (mm/dd/yy)",
# otherwise, links will need to be manually added.
addTitleToMain=true

# Tells the script how many lines the title of the main page spans.
# Used to insert the newest post at the top.
# Titles created by mkphlog are 3 lines.
# Isn't used if $addTitleToMain is false
titleLineCount=3

# Tells the script whether or not to create a RSS feed
# of the new phlog posts.
createRssFeed=true

# Tells the script whether or not to create a ATOM feed
# of the new phlog posts
createAtomFeed=true

# This is the directory in which to save the RSS feed.
rssFileDir="$gopherRoot/$phlogDirName"

# Name of the rss file
rssFileName="phlog.rss"

# This is the directory in which to save the ATOM feed.
atomFileDir="$gopherRoot/$phlogDirName"

# Name of the tom file
atomFileName="phlog.atom"

# The URL your home gopher directory. Should contain
# the $phlogDir. Ex. gopher://sdf.org/1/users/octotep/
gopherUrl="gopher://sdf.org/1/users/$(whoami)"

# The URL of your phlog. Should probably be $gopherUrl/$phlogDir/
phlogUrl="$gopherUrl/$phlogDirName"

# Create new date commands for the feeds
alias rssDate="date '+%a, %d %b %G %T %z'"
alias atomDate="date '+%Y-%m-%dT%T%z'"

#Command-line flags
silentMode=false

# Prints the help screen and exits
DisplayHelp() {
	echo "mkphlog [-hs] [file_with_post] [title] "
	echo
	echo "Updates a phlog created in the mkphlog format"
	echo "Options:"
	echo "  -s    Run the script in silent mode. As long as a file"
	echo "        with the post is specified, the script will publish"
	echo "        the post without prompting the user for any information"
	echo "        If no title is specified, the title is the filename."
	echo "        (Underscore characters are considered spaces)."
	echo
	echo "  -h    Display this help"
	echo
	echo "Created by Chris Yealy (octotep)"
	echo "The newest version can be found at:"
	echo "gopher://sdf.org/1/users/octotep/dls/mkphlog"
	echo "or"
	echo "https://bitbucket.org/octotep/mkphlog/"
	exit 0
}

# Tests for a gopher directory. Exits on failure.
TestForGopherDirectory() {
	if [ -d $gopherRoot ] ; then
		cd $gopherRoot
	else
		echo "You don't have a gopherspace set-up. Please run the mkgopher utility."
		exit 1
	fi
}

# Tests for a phlog directory. If one doesn't exist, create it.
TestForPhlogDirectory() {
	if [ -d $phlogDirName ] ; then
		cd $phlogDirName
	else
		echo -n "Do you want to create a phlog directory? (y/n) "
		read phlogDirAns
		case $phlogDirAns in
			y* | Y* ) CreatePhlogDir ;;
			n* | N* ) exit 1 ;;
			* ) exit 1 ;;
		esac
	fi
}

# Test to make sure the feed files exist
TestForFeeds () {
	if ! [ -f $rssFileDir/$rssFileName ] ; then
		CreateRssFile
	fi
	if ! [ -f $atomFileDir/$atomFileName ] ; then
		CreateAtomFile
	fi
}

# Creates the phlog directory if it dosen't already exist.
CreatePhlogDir() {
	mkdir $phlogDirName
	chmod 755 $phlogDirName
	cd $phlogDirName
	echo -n "What would you like to name your phlog? "
	read phlogNameAns
	echo $phlogNameAns > gophermap
	echo "=======================================" >> gophermap
	echo >> gophermap
	chmod 644 $gopherRoot/$phlogDirName/gophermap
	echo "Phlog directory and main gophermap file created." 
}

# Create phlog entry
CreatePhlogEntry() {
	echo "Creating today's phlog entry..."
	# Touch the main gophermap, for the SDF phlogosphere
	touch $gopherRoot/gophermap
	entryDate=`date +%m-%d-%y`
	# Make sure there isn't a post for that day, lest we overwrite it.
	if [ ! -d $entryDate ]; then
		mkdir $entryDate
		chmod 755 $entryDate
		cd $entryDate
		touch gophermap
		chmod 644 gophermap
	else
		echo "There is already a post for today."
		AskToEdit
	fi
}

# Create a base RSS file
CreateRssFile() {
	##echo "enter createRssFile"
	echo -n "Enter the RSS feed name: "
	read rssFeedName
	echo -n "Enter a RSS feed discription: "
	read rssFeedDescription
	cd $rssFileDir
	cat << EOF > $rssFileName.tmp
/rss/@version=2.0
/rss/channel/title=$(echo $rssFeedName | sed -e 's_&_&amp;_g' -e 's_<_\&lt;_g' -e 's_>_\&gt;_g' -e 's_\"_\&quot;_g' -e "s_'_\&apos;_g")
/rss/channel/description=$(echo $rssFeedDescription | sed -e 's_&_&amp;_g' -e 's_<_\&lt;_g' -e 's_>_\&gt;_g' -e 's_\"_\&quot;_g' -e "s_'_\&apos;_g")
/rss/channel/link=$phlogUrl
/rss/channel/lastBuildDate=$(rssDate)
/rss/channel/pubDate=$(rssDate)
EOF
	2xml < $rssFileName.tmp > $rssFileName.tmp2
	# The only way to control xmllint's output is with an enviroment variable
	export XMLLINT_INDENT="    "
	xmllint --encode UTF-8 --format $rssFileName.tmp2 > $rssFileName
	# Clean up
	unset XMLLINT_INDENT
	rm $rssFileName.tmp
	rm $rssFileName.tmp2
	##echo "Exit createRssFile"
}

# Update the RSS file with the new post.
UpdateRssFile() {
	##echo "Enter updateRssFile"
	if [ "$postDesc" = "" ] ; then
		postDesc=$postTitleAns
	fi
	cd $rssFileDir
	guid=$(uuid -v 4)
	xml2 < $rssFileName > $rssFileName.tmp
	# Add the new post to the feed
	sed '1,\_/rss/channel/pubDate_ {\_/rss/channel/pubDate_ a\
'"$(echo "/rss/channel/item/title=$postTitleAns" | sed 's_\&_\&amp;_g' | sed -e 's_\<_\&lt;_g' -e 's_\>_\&gt;_g' -e 's_\"_\&quot;_g' -e "s_\'_\&apos;_g")"'\
'"$(echo "/rss/channel/item/description=$postDesc" | sed 's_\&_\&amp;_g' | sed -e 's_\<_\&lt;_g' -e 's_\>_\&gt;_g' -e 's_\"_\&quot;_g' -e "s_\'_\&apos;_g")"'\
'"$(echo "/rss/channel/item/link=$phlogUrl/$entryDate")"'\
'"$(echo "/rss/channel/item/guid=$guid")"'\
'"$(echo "/rss/channel/item/pubDate=$(rssDate)")"'
	}' < $rssFileName.tmp > $rssFileName.tmp2
	# Change the last built date
	sed 's_\(/rss/channel/lastBuildDate=\).*_\1'"$(rssDate)"'_' < $rssFileName.tmp2 > $rssFileName.tmp
	# Re-create the feed
	2xml < $rssFileName.tmp > $rssFileName.tmp2
	# The only way to control xmllint's output is with an enviroment variable
	export XMLLINT_INDENT="    "
	xmllint --format $rssFileName.tmp2 > $rssFileName
	# Clean up
	unset XMLLINT_INDENT
	rm $rssFileName.tmp
	rm $rssFileName.tmp2
	##echo "exit UpdateRssFile"
}

# Create the base ATOM feed
CreateAtomFile() {
	##echo "Enter CreateAtomFile"
	echo -n "Enter the feed name: "
	read atomFeedTitle
	echo -n "Enter a feed Subtitle: "
	read atomFeedSubtitle
	cd $atomFileDir
	uuid=$(uuid -v 4)
	cat << EOF > $atomFileName.tmp
/feed/@xmlns=http://www.w3.org/2005/Atom
/feed/title=$(echo $atomFeedTitle | sed -e 's_&_&amp;_g' -e 's_<_\&lt;_g' -e 's_>_\&gt;_g' -e 's_\"_\&quot;_g' -e "s_'_\&apos;_g")
/feed/subtitle=$(echo $atomFeedSubtitle | sed -e 's_&_&amp;_g' -e 's_<_\&lt;_g' -e 's_>_\&gt;_g' -e 's_\"_\&quot;_g' -e "s_'_\&apos;_g")
/feed/link/@href=$phlogUrl
/feed/link/@rel=self
/feed/link
/feed/link/@href=$gopherUrl
/feed/id=urn:uuid:$uuid
/feed/updated=$(atomDate)
EOF
	2xml < $atomFileName.tmp > $atomFileName.tmp2
	# The only way to control xmllint's output is with an enviroment variable
	export XMLLINT_INDENT="    "
	xmllint --format $atomFileName.tmp2 > $atomFileName
	# Clean up
	unset XMLLINT_INDENT
	rm $atomFileName.tmp
	rm $atomFileName.tmp2
	##echo "exit CreateAtomFile"
}

# Update the ATOM feed with the new post
UpdateAtomFile() {
	##echo "Enter UpdateAtomFile"
	# Author tag attributes
	atomAuthor=`whoami`
	atomEmail="$atomAuthor@sdf.lonestar.org"
	if [ "$postDesc" = "" ] ; then
		postDesc=$postTitleAns
	fi
	cd $atomFileDir
	uuid=$(uuid -v 4)
	xml2 < $atomFileName > $atomFileName.tmp
	# Add the new post to the feed
	sed '1,\_/feed/updated_ {\_/feed/updated_ a\
'"$(echo "/feed/entry/title=$postTitleAns" | sed -e 's_\&_\&amp;_g' -e 's_\<_\&lt;_g' -e 's_\>_\&gt;_g' -e 's_\"_\&quot;_g' -e "s_\'_\&apos;_g")"'\
'"$(echo "/feed/entry/summary=$postDesc" | sed -e 's_\&_\&amp;_g' -e 's_\<_\&lt;_g' -e 's_\>_\&gt;_g' -e 's_\"_\&quot;_g' -e "s_\'_\&apos;_g")"'\
'"$(echo "/feed/entry/link/@href=$phlogUrl/$entryDate")"'\
'"$(echo "/feed/entry/id=urn:uuid:$uuid")"'\
'"$(echo "/feed/entry/updated=$(atomDate)")"'\
'"$(echo "/feed/entry/author/name=$atomAuthor")"'\
'"$(echo "/feed/entry/author/email=$atomEmail")"'
	}' < $atomFileName.tmp > $atomFileName.tmp2
	# Change the last built date
	sed 's_\(/feed/updated=\).*_\1'"$(atomDate)"'_' < $atomFileName.tmp2 > $atomFileName.tmp
	# Re-create the feed
	2xml < $atomFileName.tmp > $atomFileName.tmp2
	# The only way to control xmllint's output is with an enviroment variable
	export XMLLINT_INDENT="    "
	xmllint --format $atomFileName.tmp2 > $atomFileName
	# Clean up
	unset XMLLINT_INDENT
	rm $atomFileName.tmp
	rm $atomFileName.tmp2
	##echo "exit UpdateAtomFile"
}

# Updates the main phlog listing. This is where the magic happens.
UpdatePhlogListing() {
	##echo "enter UpdatePhlogListing"
	# If the user wants the post automatically added to the 
	# main page, do it.
	if [ $addTitleToMain = true ] ; then
		cd $gopherRoot/$phlogDirName/
		# Break up the gophermap
		totalLineCount=$(wc -l gophermap | sed -e 's/ //g' -e 's/gophermap//')
		linesLeft=$(echo "$totalLineCount - $titleLineCount" | bc)
		head -n $titleLineCount gophermap > title.tmp
		tail -n $linesLeft gophermap > gophermap.tmp
		# Recreate the gophermap
		rm gophermap
		cat title.tmp > gophermap
		echo -e "1${postTitleAns} (${entryDate})\t./${entryDate}" >> gophermap
		cat gophermap.tmp >> gophermap
		rm title.tmp gophermap.tmp
		chmod 644 $gopherRoot/$phlogDirName/gophermap
	fi
	cd $gopherRoot/$phlogDirName/$entryDate/
	echo $postTitleAns >> gophermap
	date "+%A %b %e %l:%M:%S %Y" >> gophermap
	echo "------------------------------" >> gophermap
	# If the user supplied a file with the text of the post, use it.
	if [ -f "$cwd/$postFile" ] ; then
		echo >> gophermap
		cat "$cwd/$postFile" >> gophermap
	fi
	echo >> gophermap
	# If the user wants feed files, update them
	if [ $createRssFeed = true ] ; then
		UpdateRssFile
	fi
	if [ $createAtomFeed = true ] ; then
		UpdateAtomFile
	fi
	##echo "exit UpdatePhlogListing"
}

AskToEdit() {
    echo -n "Would you like to edit the post with $editor? (y/n) "
	read editorAns
	case $editorAns in
		y* | Y* ) $editor $gopherRoot/$phlogDirName/$entryDate/gophermap ;;
		n* | N* ) exit 0 ;;
		* ) exit 0 ;;
	esac
	exit 0
} 

#### Main script ####

# Parse our options
while getopts "sh" optionName; do
	case $optionName in
		s) silentMode=true ;;
		h) DisplayHelp ;;
		\?) echo "Unknown parameters. Please run mkphlog -h" ; exit 1 ;;
	esac
done
shift $((OPTIND-1)); OPTIND=1

postFile="$1"

TestForGopherDirectory
TestForPhlogDirectory
TestForFeeds

# Different things for different modes
if [ $silentMode = true ] ; then
	if [ ! -e "$cwd/$1" ] ; then
		echo "Post file does not exist."
		exit 1
	fi
	# Just in case the user didn't specify a title
	if [ "$2" = "" ] ; then
		postTitleAns=$(echo $1 | sed -e 's/_/ /g') 
	else
		postTitleAns=$2
	fi
	CreatePhlogEntry
	UpdatePhlogListing
else
	echo -n "Would you like to create a phlog entry for today? (y/n) "
	read phlogAns
	case $phlogAns in
		y* | Y* ) CreatePhlogEntry ;;
		n* | N* ) exit 0 ;;
		* ) exit 1 ;;
	esac
	if [ ! -e "$cwd/$1" ] ; then
		echo "Post file does not exist. Creating new post anyway."
	fi
	# Get a title if one isn't provided
	if [ "$2" = "" ] ; then
		echo -n "Title: "
		read postTitleAns
	else
		postTitleAns=$2
	fi
	# Get a description for the feeds
	if [ $createRssFeed = true ] || [ $createAtomFeed = true ] ; then
		echo -n "Description of post: "
		read postDesc
	fi
	UpdatePhlogListing
	if [ ! -e "$cwd/$1" ] ; then
		AskToEdit
	fi
fi

exit 0
